[package]
name = "exploring_evolutionary_programming_ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
bot = { path = "./bot" }
rand = "0.8.5"

[workspace]
members = [
  "bot"
]
